prefix: "§f§l[§bLengbanlist§f§l]"
default-message: "§f[§b§oServer §f§oNetwork§f] §6当前§c已封禁 §f%s §c人 §4§n禁止私自盗取物品，破坏机器，损坏建筑！§f如遭遇此类事件，请进群处理：§bxxxxxxx"
sendtime: 5 #已分钟为单位
opensendtime: true #开启循环播报封禁人数
muted:
Model: "Default"
valid-models: "Default HuTao Furina Zhongli Keqing Xiao Ayaka Zero Herta"
models:
  Default:
    material: PAPER
  HuTao:
    material: FLOWER
  Furina:
    material: FERN
  Zhongli:
    material: STONE
  Keqing:
    material: DIAMOND
  Xiao:
    material: FEATHER
  Ayaka:
    material: ICE
  Zero:
    material: SNOWBALL
  Herta:
    material: SLIME_BALL
#-->关于本插件【Lengbanlist】，您需要知悉的：
#1.本插件在Github上开源：https://github.com/xiaoshaziYA/Lengbanlist
#2.本插件功能上绝对免费，此插件禁止倒卖，一经发现，严肃处理
#3.本插件使用MPL - 2.0开源协议开源，请您注意
#About：
#This plugin is designed to provide a portable integration of banning and querying for high - version Minecraft servers. It is fully based on the local system and offers customizable models for users to choose from. It features good performance and will be regularly updated.
#-->注意事项：
#1.您可以在爱发电支持作者，其他平台让您赞助的都是冒牌，赞助前请注意辨别，赞助代表你是自愿的，创作者不会退回费用，未成年禁止赞助：https://afdian.com/a/lengbanlist
#2.您可以在苦力怕论坛：https://klpbbs.com/thread-154852-1-1.html 找到此插件并给个好评，也可以在Github上：https://github.com/xiaoshaziYA/Lengbanlist 上给个stars！！谢谢！！！
#-->绝对知悉：
#1.本插件不支持热加载，替换插件更新后请重启服务器，确保插件正常运作
#2.本插件没有后门且在github上开源，您可以自行编译
#3.本插件不会随意收集任何信息，只作统计服务
#4.任何bug反馈前，请一定确保是本插件的bug，有的时候可能是别的插件造成的
#5.态度谦和诚恳的反馈会获得优先处理
#6.好的建议将被采纳
#7.爱发电上赞助的可获得BETA权限，获得更多福利！

#作者：Leng 
#编于：2025年2月11日